
class HelloSolution:
    
    # friend_name = unicode string
    def hello(self, friend_name):
        if not friend_name:
            raise ValueError("friend_name is required")
        else:
            return f"Hello World!"

        # raise NotImplementedError()
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????
    # IS THERE MEANT TO BE A TEST FILE FOR THIS CHALLENGE???????





